server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey
    temperature:
      exchange: temperature.exchange
      queue: temperature.queue
      routingkey: temperature.routingkey